/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorSignupRouteImport } from './routes/instructor-signup'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedInstructorsRouteImport } from './routes/_authenticated/instructors'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorSignupRoute = InstructorSignupRouteImport.update({
  id: '/instructor-signup',
  path: '/instructor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructorsRoute =
  AuthenticatedInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cancel': typeof CancelRoute
  '/instructor-signup': typeof InstructorSignupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cancel': typeof CancelRoute
  '/instructor-signup': typeof InstructorSignupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cancel': typeof CancelRoute
  '/instructor-signup': typeof InstructorSignupRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/instructor': typeof AuthenticatedInstructorRoute
  '/_authenticated/instructors': typeof AuthenticatedInstructorsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cancel'
    | '/instructor-signup'
    | '/login'
    | '/onboarding'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/instructor'
    | '/instructors'
    | '/payments'
    | '/services'
    | '/settings'
    | '/students'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cancel'
    | '/instructor-signup'
    | '/login'
    | '/onboarding'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/instructor'
    | '/instructors'
    | '/payments'
    | '/services'
    | '/settings'
    | '/students'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cancel'
    | '/instructor-signup'
    | '/login'
    | '/onboarding'
    | '/_authenticated/bookings'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/instructor'
    | '/_authenticated/instructors'
    | '/_authenticated/payments'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CancelRoute: typeof CancelRoute
  InstructorSignupRoute: typeof InstructorSignupRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor-signup': {
      id: '/instructor-signup'
      path: '/instructor-signup'
      fullPath: '/instructor-signup'
      preLoaderRoute: typeof InstructorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructors': {
      id: '/_authenticated/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthenticatedInstructorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
  }
}

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRoute
  AuthenticatedInstructorsRoute: typeof AuthenticatedInstructorsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRoute,
  AuthenticatedInstructorsRoute: AuthenticatedInstructorsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CancelRoute: CancelRoute,
  InstructorSignupRoute: InstructorSignupRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
