
ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS province TEXT,
  ADD COLUMN IF NOT EXISTS cancellation_notice_hours INT NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS cancellation_fee_cents INT NOT NULL DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS deposit_required BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS deposit_cents INT NOT NULL DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN NOT NULL DEFAULT false;
